name: MineRaidersDoor
version: 1.0.0
main: MineRaiders.MRD   # 替换为你的包名
api-version: 1.21
description: 一个简单的门插件，支持创建、开关、按钮绑定和图形菜单
author: YaoGuai,Dik
commands:
  door:
    description: 门插件主命令
    usage: /door <create|toggle|remove|bind|unbind|menu>
    aliases: [doors]
permissions:
  door.admin:
    description: 允许使用所有门命令
    default: op